name: demo

on:
  push:
    branches:
      - main

jobs:
  deploy-demo:
    runs-on: ubuntu-latest
    steps:
      - name: Build the demo
        uses: garygrossgarten/github-action-ssh@release
        with:
          host: ${{ secrets.DEMO_HOST_SECRET }}
          username: ${{ secrets.DEMO_USER_SECRET }}
          privateKey: ${{ secrets.DEMO_KEY_SECRET}}
          passphrase: ${{secrets.DEMO_PASS_SECRET}}
          command: |
            & "c:\demo.ps1"
